VAPID_PUBLIC_KEY = "BH6t-OZ4NXBVwMOdhe2_4_eVoOc4IpfNaeiD5Br7Dd5zqlzWQPRAiXRqcECyNbjew0LtXIpSVr5zFazthph-8Zc"
VAPID_PRIVATE_KEY = "_leTZKG9l1-xODC0uDRzM_I2ti60PTvjkNd1C4-ztqY"
VAPID_CLAIM_EMAIL = "test@gmail.com"